### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by viktormihalyi** [BME-MIT-IET/Urestabik-iet-2019#1]

**Comment by tamkor** [comment]
Elkezdtem.

**Comment by tamkor** [comment]
Kész. 

Hozzá kellett adni a travis.yml fájl before_install: sora után az alábbit: "-chmod +x gradlew", hogy megfelelő jogokkal tudja futtatni a travis a projektet.

**Comment by viktormihalyi** [comment]
Ellenőrizve, ok!
