### ISSUE TITLE
Use try-with-resources for file operations

### ISSUE THREAD

**Issue by viktormihalyi** [BME-MIT-IET/Urestabik-iet-2019#4]

**Comment by viktormihalyi** [comment]
fixed in https://github.com/BME-MIT-IET/Urestabik-iet-2019/commit/73d8611cff29b1ace29e595c12742f1e53e05be1 and https://github.com/BME-MIT-IET/Urestabik-iet-2019/commit/859afabdb5923b312b3ce2d283b0c271eb56d9e5

**Comment by tamkor** [comment]
Fixed.
