### ISSUE TITLE
Fix XML external entity vulnerability when importing data

### ISSUE THREAD

**Issue by viktormihalyi** [BME-MIT-IET/Urestabik-iet-2019#5]
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

**Comment by viktormihalyi** [comment]
fixed in https://github.com/BME-MIT-IET/Urestabik-iet-2019/commit/587f85030327cbcd656e09125983f7ecddcd70c1

**Comment by tamkor** [comment]
OK!
